// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Unused at runtime (the D1 driver adapter supplies the connection); this
    // only satisfies the CLI for schema/migration tooling.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
