// Custom Cloudflare Worker entry point.
//
// It re-uses OpenNext's generated fetch handler (which serves the Next.js app)
// and adds a `scheduled` handler so Cloudflare Cron Triggers can drive the
// scrape jobs — the equivalent of the old Vercel cron. The cron routes stay
// guarded by CRON_SECRET.
//
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`, so this
// file is excluded from the Next.js tsconfig and bundled by wrangler at deploy.

// @ts-ignore - generated at build time
import openNextHandler from "./.open-next/worker.js";

// Re-export OpenNext's Durable Objects so their class bindings resolve.
// @ts-ignore - generated at build time
export {
  DOQueueHandler,
  DOShardedTagCache,
  BucketCachePurge,
} from "./.open-next/worker.js";

export default {
  fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    return openNextHandler.fetch(request, env, ctx);
  },

  async scheduled(
    event: ScheduledController,
    env: { CRON_SECRET?: string },
    ctx: ExecutionContext
  ): Promise<void> {
    // The daily 13:00 UTC trigger runs the historical backfill; every other
    // trigger runs the market-watch scrape.
    const path =
      event.cron === "0 13 * * 0-4" ? "/api/cron/historical" : "/api/cron/scrape";
    const req = new Request(`https://cron.internal${path}`, {
      headers: { authorization: `Bearer ${env.CRON_SECRET ?? ""}` },
    });
    ctx.waitUntil(openNextHandler.fetch(req, env, ctx));
  },
};
