// Custom Cloudflare Worker entry point.
//
// It re-uses OpenNext's generated fetch handler (which serves the Next.js app)
// and adds a `scheduled` handler so Cloudflare Cron Triggers can drive the
// scrape jobs — the equivalent of the old Vercel cron. The cron routes stay
// guarded by CRON_SECRET.
//
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`, so this
// file is excluded from the Next.js tsconfig and bundled by wrangler at deploy.

// @ts-ignore - generated at build time
import openNextHandler from "./.open-next/worker.js";

// Re-export OpenNext's Durable Objects so their class bindings resolve.
// @ts-ignore - generated at build time
export {
  DOQueueHandler,
  DOShardedTagCache,
  BucketCachePurge,
} from "./.open-next/worker.js";

export default {
  fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    return openNextHandler.fetch(request, env, ctx);
  },

  async scheduled(
    event: ScheduledController,
    env: { CRON_SECRET?: string },
    ctx: ExecutionContext
  ): Promise<void> {
    // Dispatch by schedule (matched on the "minute hour" prefix so it stays
    // correct if the day-of-week part changes):
    //   0 13 * * ...  -> equity historical backfill
    //   0 14 * * ...  -> sukuk board + historical trades (daily incremental)
    //   0 15 * * ...  -> sukuk universe analysis (Claude commentary)
    //   */5 ...       -> equity market-watch scrape
    let path = "/api/cron/scrape";
    if (event.cron.startsWith("0 13 ")) path = "/api/cron/historical";
    else if (event.cron.startsWith("0 14 ")) path = "/api/cron/sukuk?mode=daily";
    else if (event.cron.startsWith("0 15 ")) path = "/api/cron/sukuk-analyze";
    const req = new Request(`https://cron.internal${path}`, {
      headers: { authorization: `Bearer ${env.CRON_SECRET ?? ""}` },
    });
    ctx.waitUntil(openNextHandler.fetch(req, env, ctx));
  },
};
